# Use an official Node runtime as a parent image
FROM node:18-alpine

# Set environment variables
ENV NODE_ENV=development

# Set working directory
WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm ci

# Copy project files
COPY . .

# Expose port
EXPOSE 3000

# Start the application in development mode
CMD ["npm", "run", "dev"]